# Generated by Django 4.2.6 on 2023-10-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('content', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='превью')),
            ],
            options={
                'verbose_name': 'куры',
                'verbose_name_plural': 'курсы',
            },
        ),
    ]
